image: maven:3.8.8-eclipse-temurin-17-alpine

stages:
  - build
  - test
# Cache Maven dependencies to speed up builds
cache:
  paths:
    - .m2/repository
build:
  stage: build
  script:
    - echo "Building Cart Shopping Project"
    - mvn clean install -DskipTests

test:
  stage: test
  script:
    - echo "Running Tests Cart Shopping Project"
    - mvn test